CREATE TABLE IF NOT EXISTS "User" (
  "id" TEXT PRIMARY KEY,
  "email" TEXT NOT NULL UNIQUE,
  "fullName" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "accountStatus" TEXT NOT NULL DEFAULT 'ACTIVE',
  "trainingRecordsJson" TEXT NOT NULL DEFAULT '[]',
  "passwordHash" TEXT NOT NULL,
  "phone" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "accountStatus" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "trainingRecordsJson" TEXT NOT NULL DEFAULT '[]';

CREATE TABLE IF NOT EXISTS "Job" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT NOT NULL,
  "companyJobNumber" TEXT NOT NULL,
  "customerJobNumber" TEXT NOT NULL,
  "siteAddress" TEXT NOT NULL,
  "externalInfo" TEXT NOT NULL DEFAULT '',
  "internalInfo" TEXT NOT NULL DEFAULT '',
  "status" TEXT NOT NULL,
  "scheduledFor" TIMESTAMP,
  "scheduledTo" TIMESTAMP,
  "scheduledStartTime" TEXT,
  "scheduledEndTime" TEXT,
  "scheduledDays" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "dailyAssignmentsJson" TEXT NOT NULL DEFAULT '{}',
  "assignedOperativeIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "companyJobNumber" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "customerJobNumber" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "externalInfo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "internalInfo" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "scheduledTo" TIMESTAMP;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "scheduledStartTime" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "scheduledEndTime" TEXT;
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "scheduledDays" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "dailyAssignmentsJson" TEXT NOT NULL DEFAULT '{}';
ALTER TABLE "Job" ADD COLUMN IF NOT EXISTS "assignedOperativeIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
UPDATE "Job" SET "companyJobNumber" = COALESCE("companyJobNumber", "id") WHERE "companyJobNumber" IS NULL;
UPDATE "Job" SET "customerJobNumber" = COALESCE("customerJobNumber", "id") WHERE "customerJobNumber" IS NULL;
ALTER TABLE "Job" ALTER COLUMN "companyJobNumber" SET NOT NULL;
ALTER TABLE "Job" ALTER COLUMN "customerJobNumber" SET NOT NULL;

CREATE TABLE IF NOT EXISTS "Task" (
  "id" TEXT PRIMARY KEY,
  "jobId" TEXT NOT NULL REFERENCES "Job"("id") ON DELETE CASCADE,
  "title" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "FormDefinition" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "version" INTEGER NOT NULL,
  "schemaJson" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "TimesheetEntry" (
  "id" TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE,
  "startedAt" TIMESTAMP NOT NULL,
  "endedAt" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Asset" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "serialNumber" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "Document" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "storagePath" TEXT NOT NULL,
  "mimeType" TEXT NOT NULL,
  "jobId" TEXT REFERENCES "Job"("id") ON DELETE CASCADE,
  "visibility" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "jobId" TEXT REFERENCES "Job"("id") ON DELETE CASCADE;
ALTER TABLE "Document" ADD COLUMN IF NOT EXISTS "visibility" TEXT;

CREATE TABLE IF NOT EXISTS "Notification" (
  "id" TEXT PRIMARY KEY,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "channel" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "AuditLog" (
  "id" TEXT PRIMARY KEY,
  "action" TEXT NOT NULL,
  "entity" TEXT NOT NULL,
  "entityId" TEXT NOT NULL,
  "actorId" TEXT,
  "metadata" JSONB,
  "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
